<?php

namespace c0710204\admin\settingsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * settingsItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class settingsItemRepository extends EntityRepository
{
}
