<?php

namespace c0710204\test\sy2Bundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * booksRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class booksRepository extends EntityRepository
{
}
